<?php
/**
 * This file has been automatically generated by Pomm's generator.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace db\Db\PublicSchema\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * Frame
 *
 * Structure class for relation public.frame.
 * 
 * Class and fields comments are inspected from table and fields comments.
 * Just add comments in your database and they will appear here.
 * @see http://www.postgresql.org/docs/9.0/static/sql-comment.html
 *
 *
 *
 * @see RowStructure
 */
class Frame extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     *
     * @access public
     */
    public function __construct()
    {
        $this
            ->setRelation('public.frame')
            ->setPrimaryKey(['idframe'])
            ->addField('idframe', 'varchar')
            ->addField('startframe', 'timestamp')
            ->addField('stopframe', 'timestamp')
            ->addField('idproject', 'int4')
            ;
    }
}
